-- 코드를 입력하




# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS,B.SCORE
# FROM REST_INFO A
# JOIN (
#     SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
#     FROM REST_REVIEW
#     GROUP BY REST_ID
# ) AS B ON A.REST_ID = B.REST_ID
# WHERE A.ADDRESS LIKE '%서울%'
# ORDER BY B.SCORE DESC, A.FAVORITES DESC;

SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A
JOIN REST_REVIEW AS B
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC;



# SELECT * FROM REST_INFO;