-- 코드를 작성해주세요
-- SELECT * FROM HR_DEPARTMENT; -- 부서 id, 국문 부서명, 영문 부서명, 부서위치

-- SELECT * FROM HR_EMPLOYEES; -- 사번, 이름, 부서ID, 직책, 이메일, 전화번호, 입사일, 연봉 

-- SELECT * FROM HR_GRADE; -- 사번, 연도, 반기, 평가점수 

-- 사원별 성과금 정보 

#SELECT A.EMP_NO, B.SCORE
# FROM HR_EMPLOYEES A
# JOIN HR_GRADE B
# ON A.EMP_NO = B.EMP_NO;

# SELECT SCORE,
# CASE WHEN SCORE>=96 THEN 'S'
#      WHEN SCORE>=90 THEN 'A'
#      WHEN SCORE>=80 THEN 'B'
#      ELSE 'C'
#      END AS GRADE,
     
# CASE WHEN SCORE>=96 THEN 0.2
#      WHEN SCORE>=90 THEN 0.15
#      WHEN SCORE>=80 THEN 0.1
#      ELSE 0
#      END AS BONUS
# FROM HR_GRADE
#GROUP BY SCORE

SELECT A.EMP_NO, A.EMP_NAME,B.GRADE,B.BONUS * A.SAL AS BONUS
FROM HR_EMPLOYEES A

JOIN (SELECT EMP_NO,
CASE WHEN AVG(SCORE)>=96 THEN 'S'
     WHEN AVG(SCORE)>=90 THEN 'A'
     WHEN AVG(SCORE)>=80 THEN 'B'
     ELSE 'C'
     END AS GRADE,
     
CASE WHEN AVG(SCORE)>=96 THEN 0.2
     WHEN AVG(SCORE)>=90 THEN 0.15
     WHEN AVG(SCORE)>=80 THEN 0.1
     ELSE 0
     END AS BONUS
FROM HR_GRADE
GROUP BY EMP_NO) B
ON A.EMP_NO = B.EMP_NO
ORDER BY EMP_NO ;



