-- 코드를 입력하세요

-- 아이스크림 총 주문량 > 3000 AND FRUIT_BASEED

# SELECT * FROM ICECREAM_INFO;

SELECT A.FLAVOR 
FROM ICECREAM_INFO AS A
RIGHT OUTER JOIN FIRST_HALF AS B
ON A.FLAVOR = B.FLAVOR
WHERE A.INGREDIENT_TYPE = 'fruit_based' AND B.TOTAL_ORDER>3000;