-- 코드를 입력하세요
SELECT * FROM USED_GOODS_BOARD;
SELECT * FROM USED_GOODS_REPLY;

-- 2022년 10월에 작성된 게시글 
-- DATE_FORMAT(CREATE_DATE, '%y-%m-%d') AS CREATED_DATE
SELECT A.TITLE,B.BOARD_ID,B.REPLY_ID,B.WRITER_ID,B.CONTENTS,
DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD AS A
JOIN USED_GOODS_REPLY AS B 
ON A.BOARD_ID = B.BOARD_ID
WHERE DATE_FORMAT(A.CREATED_DATE,'%Y-%m') = '2022-10'
ORDER BY B.CREATED_DATE, A.TITLE ; 